services:
  application:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ${CONTAINER_NAME}
    command: ["uvicorn", "app:server", "--reload", "--proxy-headers", "--host", "0.0.0.0", "--port", "${PORT}"]
    volumes:
      - "./${APPLICATION_DIR}:/root/${APPLICATION_DIR}"
    ports:
      - "${PORT}:${PORT}"
    env_file:
      - .env
    depends_on:
      - database

  database:
    image: postgres:latest
    container_name: ${POSTGRES_DB}
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "${POSTGRES_PORT}:${POSTGRES_PORT}"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: